# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtlocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gplace',
            name='reference_sha1',
            field=models.CharField(blank=True, help_text=b"A sha1 of the reference - used for ensuring uniqueness of reference's.", max_length=40, null=True, unique=True),
        ),
    ]
