# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('exception', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[(b'note', b'Note'), (b'error', b'Error'), (b'warning', b'Warning')], max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='InputRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('exception', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(choices=[(1, b'Running'), (3, b'Failed'), (2, b'Complete'), (4, b'Partial Import')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='inputnote',
            name='input_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtimport.InputRecord'),
        ),
    ]
